config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'splash#index'
  # get '/users/:id', to: 'groups#index', as: 'user_root'
  resources :groups do
    resources :conversions
    resources :group_conversions
  end
  resources :users
  # resources :conversions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/conversion.rb
class Conversion < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_conversions, class_name: 'GroupConversion', foreign_key: :conversion_id

  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
  # GET /conversions or /conversions.json
  def index
    @conversions = Conversion.where(author_id: current_user.id)
    @group = Group.find(params[:group_id])
  end

  # GET /conversions/1 or /conversions/1.json
  def show; end

  # GET /conversions/new
  def new
    @conversion = Conversion.new
    @group = Group.find(params[:group_id])
  end

  # GET /conversions/1/edit
  def edit; end

  # POST /conversions or /conversions.json
  def create
    @conversion = Conversion.new(conversion_params)
    @conversion.author_id = current_user.id
    respond_to do |format|
      if @conversion.save
        format.html { redirect_to group_conversions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversions/1 or /conversions/1.json
  def update
    respond_to do |format|
      if @conversion.update(conversion_params)
        format.html { redirect_to conversion_url(@conversion), notice: 'Conversion was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversions/1 or /conversions/1.json
  def destroy
    @conversion.destroy

    respond_to do |format|
      format.html { redirect_to conversions_url, notice: 'Conversion was successfully destroyed.' }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def conversion_params
    params.require(:conversion).permit(:author_id, :amount, :name)
  end
end

app/helpers/conversions_helper.rb
module ConversionsHelper
end

app/views/conversions/_form.html.erb
<%= form_with(model: conversion, url: group_conversions_path) do |form| %>
  <% if conversion.errors.any? %>
    <div style="color: red">
        <% conversion.errors.each do |error| %>
          <%= error.full_message %>
        <% end %>
    </div>
  <% end %>
  <div class="navbar">
    <%= link_to "🢀", "/groups/#{@group.id}", class: 'back-link'%>
    <p class='nav-text nav-text-new'>NEW TRANSACTION</p>
    <%= form.submit 'Create Transaction', class: 'login-submit-btn' %>
  </div>
  <div class="login-fields">
    <%= form.text_field :name, placeholder: 'Name', class: 'login-field' %>
    <%= form.number_field :amount, step: 0.1, placeholder: 'Amount', class: 'login-field' %>
  </div>
<% end %>

app/views/conversions/edit.html.erb
<h1>Editing conversion</h1>

<%= render "form", conversion: @conversion %>

<br>

<div>
  <%= link_to "Show this conversion", @conversion %> |
  <%= link_to "Back to conversions", conversions_path %>
</div>

app/views/conversions/index.html.erb
<div class="home-page">
  <div class="navbar">
      <%= link_to "🢀", '/', class: 'back-link'%>
      <p class='nav-text'>DETAILS</p>
      <div></div>
  </div>
  <div class="details">
    <div class="detail">
      <div id="<%= dom_id @group %>" class="category-unit">
        <div class="category-details">
          <img src=<%= @group.icon %>" alt="<%= @group.name %>" />
          <%= link_to @group.name, group_path(@group), class: 'category-name' %>
        </div>
        <p class="total-price">Total Transactions: $<%= @group.total_conversions %></p>
      </div>
    </div>
    <% @group.group_conversions.each do |group_conversion| %>
    <div class="category">
      <div class="category-unit">
        <div>
          <h4>Transaction N: <%= group_conversion.conversion.id %></h4>
          <p><%= group_conversion.conversion.name %></p>
        </div>
        <p class="total-price">$<%= group_conversion.conversion.amount %></p>
      </div>
    </div>
    <% end %>
  </div>
  <div>
    <%= form_with(model: GroupConversion.new, url: group_group_conversions_path(@group), method: :post) do |f| %>
      <div class="form-transaction">
        <div class="form-transaction-option"><%= f.collection_select :conversion_id,  @conversions, :id, :name %></div>
        <div><%= f.submit 'Add transaction to this group', class: 'form-transaction-btn' %></div>
      </div>
    <% end %>
    <div class="add-btn-container">
      <%= button_to "Add a new transaction", new_group_conversion_path(@group), class: 'add-btn', method: :get %>
    </div>
</div>

app/views/conversions/new.html.erb
<%= render "form", conversion: @conversion %>

app/views/conversions/show.html.erb
<h1>Conversions</h1>

<div id="conversions">
<% @group.group_conversions.each do |group_conversion| %>
  <p>
    <strong>Name:</strong>
    <%= group_conversion.conversion.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= group_conversion.conversion.amount %>
  </p>
<% end %>

</div> 

<%= link_to "New conversion", new_conversion_path %>


<div>
  <%= link_to "Edit this conversion", edit_conversion_path(@conversion) %> |
  <%= link_to "Back to conversions", conversions_path %>

  <%= button_to "Destroy this conversion", @conversion, method: :delete %>
</div>