config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'splash#index'
  # get '/users/:id', to: 'groups#index', as: 'user_root'
  resources :groups do
    resources :conversions
    resources :group_conversions
  end
  resources :users
  # resources :conversions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_conversions, class_name: 'GroupConversion', foreign_key: :group_id
  has_many :conversions, through: :group_conversions

  validates :name, presence: true
  validates :icon, presence: true
  # sum of all conversions in the group
  def total_conversions
    conversions.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @conversions = Conversion.where(author_id: current_user.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:icon, :name, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
        <% group.errors.each do |error| %>
          <%= error.full_message %>
        <% end %>
    </div>
  <% end %>
  <div class="navbar">
      <%= link_to "🢀", groups_path, class: 'back-link'%>
      <p class='nav-text'>NEW CATEGORY</p>
      <%= form.submit class: 'login-submit-btn' %>
  </div>
  <div class="login-fields">
    <%= form.text_field :icon, placeholder: 'icon url e.g: https://images.com/pic.png', class: 'login-field' %>
    <%= form.text_field :name, placeholder: 'Category name', class: 'login-field' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="category-unit">
    <div class="category-details">
      <img src=<%= group.icon %>" alt="<%= group.name %>" />
      <%= link_to group.name, group_path(group), class: 'category-name' %>
    </div>
    <p class="total-price">$<%= group.total_conversions %></p>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="home-page">
  <div class="navbar">
      <%= link_to "🢀", :back, class: 'back-link'%>
      <p class='nav-text'>CATEGORY</p>
      <div><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'user-btn' %></div>
  </div>
  <div class="categories">
    <% @groups.each do |group| %>
    <div class="category">
      <%= render group %>
    </div>
    <% end %>
  </div>
  <div class="add-btn-container">
  <%= button_to "Add a new category", new_group_path, class: 'add-btn', method: :get %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

</div>

app/views/groups/show.html.erb
<div class="home-page">
  <div class="navbar">
      <%= link_to "🢀", '/', class: 'back-link'%>
      <p class='nav-text'>DETAILS</p>
      <div></div>
  </div>
  <div class="details">
    <div class="detail">
      <div id="<%= dom_id @group %>" class="category-unit">
        <div class="category-details">
          <img src=<%= @group.icon %>" alt="<%= @group.name %>" />
          <%= link_to @group.name, group_path(@group), class: 'category-name' %>
        </div>
        <p class="total-price">Total Transactions: $<%= @group.total_conversions %></p>
      </div>
    </div>
    <% @group.group_conversions.order(created_at: :desc).each do |group_conversion| %>
    <div class="category">
      <div class="category-unit">
        <div>
          <h4>Transaction N: <%= group_conversion.conversion.id %></h4>
          <p><%= group_conversion.conversion.name %></p>
        </div>
        <p class="total-price">$<%= group_conversion.conversion.amount %></p>
      </div>
    </div>
    <% end %>
  </div>
  <div>
    <%= form_with(model: GroupConversion.new, url: group_group_conversions_path(@group), method: :post) do |f| %>
      <div class="form-transaction">
        <div class="form-transaction-option"><%= f.collection_select :conversion_id,  @conversions, :id, :name %></div>
        <div><%= f.submit 'Add transaction to this group', class: 'form-transaction-btn' %></div>
      </div>
    <% end %>
    <div class="add-btn-container">
      <%= button_to "Add a new transaction", new_group_conversion_path(@group), class: 'add-btn', method: :get %>
    </div>
</div>